### ISSUE TITLE
[Maintenance] Convert build to bankai or webpack. budo is just for quick prototyping and doesn't work well: errors on reload, and missing 'hot-reload'

### ISSUE THREAD

**Issue by 10chars** [stagfoo/bazza#18]

**Comment by 10chars** [comment]
Created webpack branch but will continue dev the budo until @stagfoo has checked it

**Comment by stagfoo** [comment]
budo hot reload worked for me but yer its only for quick testing, I kept the webpack in from your cleanup commit in jquery version lets just run with that
